// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FiFoA-Iu8rQQmzBGl7TpzSR8FQMfGjs',
    appId: '1:988452585960:web:f94b5baf4e2ef9119e645d',
    messagingSenderId: '988452585960',
    projectId: 'beesmart-de79c',
    authDomain: 'beesmart-de79c.firebaseapp.com',
    storageBucket: 'beesmart-de79c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJKG0sjIUjjBDj2ErZwPrHaNzQMoTEqCw',
    appId: '1:988452585960:android:2b0b8c0f2d48be409e645d',
    messagingSenderId: '988452585960',
    projectId: 'beesmart-de79c',
    storageBucket: 'beesmart-de79c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlakbgrnjxCEzMr5yP4yfEO5oj8qM9S0',
    appId: '1:988452585960:ios:af128672c7326bb49e645d',
    messagingSenderId: '988452585960',
    projectId: 'beesmart-de79c',
    storageBucket: 'beesmart-de79c.appspot.com',
    iosClientId: '988452585960-4aoudbdamhvamd6e30us3i9vbni42olu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOlakbgrnjxCEzMr5yP4yfEO5oj8qM9S0',
    appId: '1:988452585960:ios:3ffe67dfe861d6ac9e645d',
    messagingSenderId: '988452585960',
    projectId: 'beesmart-de79c',
    storageBucket: 'beesmart-de79c.appspot.com',
    iosClientId: '988452585960-72e6q9ol55n3gqdb77ns2ggtj8uoafts.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp.RunnerTests',
  );
}
